name: CI - Publish
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      ref:
        description: 'The ref (tag, branch or commit) to publish'
        required: false
        default: 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:

    runs-on: ubuntu-latest

    permissions:
      contents: read # For checking out
      packages: write # For publishing the container images

    steps:
      - name: Set the container image tag name
        run: |
          # Use the ref from the input or from the github event (push to main)
          REF=${{ github.event_name == 'workflow_dispatch' && inputs.ref || github.ref }}

          # Remove prefix from the tag name (ref/heads/)
          TAG_NAME="${REF##*/}"

          # Set the tag as an environment variable
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          ref: ${{ env.TAG_NAME }}

      - name: Login to GitHub container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata for labeling the published images
        id: metadata
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and publish - Player Tracker
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: ./src/PlayerStatus/Apps/MlbTheShowForecaster.PlayerStatus.Apps.PlayerTracker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}/player-tracker:latest
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}/player-tracker:${{ env.TAG_NAME }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and publish - Performance Tracker
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: ./src/Performance/Apps/MlbTheShowForecaster.Performance.Apps.PerformanceTracker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}/performance-tracker:latest
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}/performance-tracker:${{ env.TAG_NAME }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and publish - Marketplace Watcher
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: ./src/GameCards/Apps/MlbTheShowForecaster.GameCards.Apps.MarketplaceWatcher/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}/marketplace-watcher:latest
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}/marketplace-watcher:${{ env.TAG_NAME }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and publish - Gateway
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: ./src/Apps/MlbTheShowForecaster.Apps.Gateway/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}/gateway:latest
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}/gateway:${{ env.TAG_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
